#!/bin/bash
SERVER='eu1.cloud.thethings.network'
TOPIC='#'
APPID='wimunet-application01'
APIKEY='NNSXS.UMBJVX3XHUE3BCY5A3UNSO354HO6DVRXHSYZENQ.FI6FFS6SO4MZBGNZU3WDIERUJLQ7REHMMXK6UGXLCYISOSRN3SPA'

mosquitto_sub -d -h $SERVER -u $APPID -P $APIKEY -p 1883 -t $TOPIC
